title: "庶民笔记"
url: https://kangshumin.github.io     # site url
baseurl: "/bj"                        # apply repo name if use it under gh-pages branch

gems:
  - jemoji

collections:
  running:
  kai:
  books:
  quotations:
    output: true
    permalink: /bj/quotations/:title/
